export const TIP_OPTIONS = {
  mancare: [
    "Meniu de Post",
    "Mic Dejun 09:00 - 11:00",
    "Aperitive",
    "Paste",
    "Bucate Calde",
    "Peste",
    "Garnituri",
    "Burger",
    "Salate",
    "Supe",
    "SUSHI",
    "Gustari la Bere / Vin",
    "Kids Menu",
    "Sosuri",
    "Desert",
  ],
  bauturi: [
    "Bere la halba 500ml",
    "Bere la halba 330ml",
    "Bauturi Racoritoare",
    "Cocktails",
    "Shots",
    "Bauturi Alcoolice",
    "Tincturi de Casa",
    "Vinuri Albe",
    "Vinuri Rosii",
    "Vinuri Roze",
    "Vinuri Spumante",
    "Bauturi calde",
    "Topping la Cafea",
  ],
};
